# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_01.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(180, 290)
        MainWindow.setMinimumSize(QtCore.QSize(180, 290))
        MainWindow.setMaximumSize(QtCore.QSize(180, 290))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setUnderline(False)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lb_Resposta = QtWidgets.QTextBrowser(self.centralwidget)
        self.lb_Resposta.setGeometry(QtCore.QRect(10, 180, 161, 51))
        self.lb_Resposta.setObjectName("lb_Resposta")
        self.nt_Calcular = QtWidgets.QPushButton(self.centralwidget)
        self.nt_Calcular.setGeometry(QtCore.QRect(40, 150, 101, 23))
        self.nt_Calcular.setObjectName("nt_Calcular")
        self.ent_Inicial = QtWidgets.QSpinBox(self.centralwidget)
        self.ent_Inicial.setGeometry(QtCore.QRect(110, 80, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ent_Inicial.setFont(font)
        self.ent_Inicial.setMinimum(2)
        self.ent_Inicial.setMaximum(36)
        self.ent_Inicial.setObjectName("ent_Inicial")
        self.ent_Final = QtWidgets.QSpinBox(self.centralwidget)
        self.ent_Final.setGeometry(QtCore.QRect(110, 110, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ent_Final.setFont(font)
        self.ent_Final.setMinimum(2)
        self.ent_Final.setMaximum(36)
        self.ent_Final.setObjectName("ent_Final")
        self.lb_Final = QtWidgets.QLabel(self.centralwidget)
        self.lb_Final.setGeometry(QtCore.QRect(20, 110, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_Final.setFont(font)
        self.lb_Final.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Final.setObjectName("lb_Final")
        self.lb_Inicial = QtWidgets.QLabel(self.centralwidget)
        self.lb_Inicial.setGeometry(QtCore.QRect(10, 80, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_Inicial.setFont(font)
        self.lb_Inicial.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lb_Inicial.setObjectName("lb_Inicial")
        self.lb_Entrada = QtWidgets.QLabel(self.centralwidget)
        self.lb_Entrada.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_Entrada.setFont(font)
        self.lb_Entrada.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_Entrada.setObjectName("lb_Entrada")
        self.ent_Entrada = QtWidgets.QTextEdit(self.centralwidget)
        self.ent_Entrada.setGeometry(QtCore.QRect(10, 40, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ent_Entrada.setFont(font)
        self.ent_Entrada.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ent_Entrada.setObjectName("ent_Entrada")
        self.copyright_Txt = QtWidgets.QTextBrowser(self.centralwidget)
        self.copyright_Txt.setGeometry(QtCore.QRect(20, 240, 141, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.copyright_Txt.setFont(font)
        self.copyright_Txt.setWhatsThis("")
        self.copyright_Txt.setAutoFillBackground(True)
        self.copyright_Txt.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.copyright_Txt.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.copyright_Txt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.copyright_Txt.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.copyright_Txt.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.copyright_Txt.setOverwriteMode(False)
        self.copyright_Txt.setObjectName("copyright_Txt")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 180, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nt_Calcular.setText(_translate("MainWindow", "Calcular"))
        self.lb_Final.setText(_translate("MainWindow", "Base final:"))
        self.lb_Inicial.setText(_translate("MainWindow", "Base inicial:"))
        self.lb_Entrada.setText(_translate("MainWindow", "Número:"))
        self.copyright_Txt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">COPYRIGHT © 2020 KINGS</span></p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:7pt;\">All rights reserved</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
